services:
  app-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "pgpassword"
    ports:
      - "5432:5432"
  auth-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "pgpassword"
    ports:
      - "5433:5432"